name: All features

on:
  push:
    branches:
      - '/feat/**'  # matches every branch starts by feat/

jobs:
  all-features:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)

