name: All ts files

on:
  push:
    branches:
      - '**'  # matches every branch
    paths:
      - '**.ts' # with ts extension

jobs:
  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)

