name: Exos avec node-app

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        working-directory: /node-app
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        working-directory: /node-app
      - run: npm ci
        working-directory: /node-app
      - run: npm test
        working-directory: /node-app

  build-matrix-node-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 12, 14, 16 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v3
        working-directory: /node-app
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
        working-directory: /node-app
      - run: npm ci
        working-directory: /node-app
      - run: npm test
        working-directory: /node-app

  build-matrix-unbuntu-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [14.x, 15.x, 16.x]

    name: Node.js ${{ matrix.node-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        working-directory: /node-app

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        working-directory: /node-app
      - run: npm ci
        working-directory: /node-app
      - run: npm test
        working-directory: /node-app
  
  node-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://node:alpine
        working-directory: /node-app
      - run: npm ci
        working-directory: /node-app
      - run: npm test
        working-directory: /node-app