name: Dev workflows

on:
  push:
    branches:
      - 'dev'

jobs:
  only-dev-push:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)

