name: Pull request closed

on:
  pull_request:
    types: [closed]


jobs:
  pr-closed:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)

