name: Scheduled every hour and half

on:
  schedule:
    - cron:  '0 0-21/3 * * *'

jobs:
  every-hour-and-half:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)

